services:
  postgres:
    image: postgres:15-alpine
    container_name: sunready-postgres
    environment:
      POSTGRES_USER: sunready
      POSTGRES_PASSWORD: sunready
      POSTGRES_DB: sunready
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sunready"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sunready-api
    environment:
      DATABASE_URL: postgres://sunready:sunready@postgres:5432/sunready?sslmode=disable
      JWT_SECRET: your-secret-key-change-in-production
      PORT: 8080
      ENV: development
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
