services:
  postgres-sunready:
    image: postgres:15-alpine
    container_name: sunready-postgres
    environment:
      POSTGRES_USER: sunready
      POSTGRES_PASSWORD: sunready
      POSTGRES_DB: sunready
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sunready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sunready-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: build/Dockerfile.sunready
    container_name: sunready-api
    environment:
      DATABASE_URL: ""
      JWT_SECRET: ""
      PORT: "8080"
      ENV: "production"
      LIGHTFUSION_API: "http://localhost:8085"
      LIGHTFUSION_EMAIL: ""
      LIGHTFUSION_PASSWORD: ""
    ports:
      - "8080:8080"
    depends_on:
      postgres-sunready:
        condition: service_healthy
    networks:
      - sunready-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  sunready-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
