services:
  postgres-sunready:
    image: postgres:15-alpine
    container_name: sunready-postgres
    environment:
      POSTGRES_USER: sunready
      POSTGRES_PASSWORD: sunready
      POSTGRES_DB: sunready
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sunready"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sunready-api
    environment:
      DATABASE_URL: postgres://sunready:sunready@postgres-sunready:5432/sunready?sslmode=disable
      JWT_SECRET: sunready
      PORT: 8080
      ENV: development
      LIGHTFUSION_API: https://api.lightfusion.com
      LIGHTFUSION_API_KEY: your-api-key-here
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      postgres-sunready:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
